# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-18 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('docker_image', models.TextField(default='')),
                ('exec_command', models.TextField(default='')),
                ('exec_args', models.TextField(default='')),
                ('cpu_request', models.IntegerField(default=100)),
                ('mem_request', models.IntegerField(default=100)),
                ('cpu_limit', models.IntegerField(default=100)),
                ('mem_limit', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommandVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('value', models.TextField(default='')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='*', max_length=255)),
                ('day', models.CharField(default='*', max_length=255)),
                ('hour', models.CharField(default='*', max_length=255)),
                ('minute', models.CharField(default='*', max_length=255)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pod_id', models.TextField(default='')),
                ('pod_creation_log', models.TextField(default='')),
                ('status', models.CharField(default='', max_length=255)),
                ('message', models.TextField(default='')),
                ('log', models.TextField(default='')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Command')),
            ],
        ),
    ]
