# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='timeout',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='crontab',
            name='num_process',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='process',
            name='time_created',
            field=models.CharField(default='', max_length=255),
        ),
    ]
