# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-25 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170422_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='namespace',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='process',
            name='namespace',
            field=models.CharField(default='', max_length=255),
        ),
    ]
