# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20170425_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='time_created',
        ),
    ]
